export const DELETE_TALENT = "DELETE_TALENT";
export const NEW_TALENT = "NEW_TALENTS";
export const GET_TALENTS = "GET_TALENTS";
export const UPDATE_TALENT = "UPDATE_TALENT";
export const EXCLUDE_TALENT = "EXCLUDE_TALENT";
export const INCLUDE_TALENT = "INCLUDE_TALENT";

export const START_SESSION = "START_SESSION";
export const STOP_SESSION = "STOP_SESSION";
export const POLL_SESSION = "POLL_SESSION";